# Generated by Django 5.0.4 on 2024-11-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_remove_profile_user_recipe_image_recipe_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
    ]
