# Generated by Django 5.0.4 on 2024-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_remove_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dietary_preferences',
            field=models.CharField(blank=True, help_text='Comma-separated dietary preferences (e.g., vegan, keto).', max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', help_text='Select the difficulty level.', max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Comma-separated list of ingredients.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='Step-by-step instructions.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(blank=True, help_text="JSON format for nutrition info (e.g., {'Calories': 200, 'Protein': '10g'}).", null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Preparation time in minutes.'),
        ),
    ]
