# Generated by Django 5.1.3 on 2024-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0007_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_preferences',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='difficulty',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(help_text='Comma-separated list of ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(help_text='Comma-separated list of instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nutrition',
            field=models.JSONField(blank=True, help_text='Dictionary of nutrition facts', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
